/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

/**
 *
 * @author Henrique
 */
public class DashBoardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    public DashBoardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        menuChamado = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        menuEquipamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuConsultaChamado = new javax.swing.JMenuItem();
        menuChamadoUsuario = new javax.swing.JMenuItem();
        menuConsultaEquipamentos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 41, 61));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        jMenu4.setText("Cadastros");

        menuChamado.setText("Chamado");
        menuChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChamadoActionPerformed(evt);
            }
        });
        jMenu4.add(menuChamado);

        menuUsuario.setText("Usuário");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(menuUsuario);

        menuEquipamento.setText("Equipamento");
        menuEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEquipamentoActionPerformed(evt);
            }
        });
        jMenu4.add(menuEquipamento);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Consultas");

        menuConsultaChamado.setText("Chamados");
        menuConsultaChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaChamadoActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsultaChamado);

        menuChamadoUsuario.setText("Usuários");
        menuChamadoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChamadoUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuChamadoUsuario);

        menuConsultaEquipamentos.setText("Equipamentos");
        menuConsultaEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaEquipamentosActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsultaEquipamentos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sobre");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChamadoActionPerformed
        ChamadoView chamadoView = new ChamadoView();
        
        chamadoView.setVisible(true);
    }//GEN-LAST:event_menuChamadoActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        UsuarioView usuarioView = new UsuarioView();
        
        usuarioView.setVisible(true);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEquipamentoActionPerformed
        EquipamentoView equipamentoView = new EquipamentoView();
        
        equipamentoView.setVisible(true);
    }//GEN-LAST:event_menuEquipamentoActionPerformed

    private void menuConsultaEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaEquipamentosActionPerformed
        ConsultaEquipamentoView consultaEquipamentoView = new ConsultaEquipamentoView();
        consultaEquipamentoView.setVisible(true);
    }//GEN-LAST:event_menuConsultaEquipamentosActionPerformed

    private void menuConsultaChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaChamadoActionPerformed
        ConsultaChamadoView consultaChamadoView = new ConsultaChamadoView();
        consultaChamadoView.setVisible(true);
    }//GEN-LAST:event_menuConsultaChamadoActionPerformed

    private void menuChamadoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChamadoUsuarioActionPerformed
        ConsultaUsuarioView consultaUsuarioView = new ConsultaUsuarioView();
        consultaUsuarioView.setVisible(true);
    }//GEN-LAST:event_menuChamadoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuChamado;
    private javax.swing.JMenuItem menuChamadoUsuario;
    private javax.swing.JMenuItem menuConsultaChamado;
    private javax.swing.JMenuItem menuConsultaEquipamentos;
    private javax.swing.JMenuItem menuEquipamento;
    private javax.swing.JMenuItem menuUsuario;
    // End of variables declaration//GEN-END:variables
}
